how to contribute part added to redme.md file
grafana/k6-learn pull request #24
Opened 2023-07-07 13:31 UTC by kwidera

I contribute so more people can contribute.

2023-07-07 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-learn?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-learn?pullRequest=24) before we can accept your contribution.<br/><hr/>**kwide_sftsrv** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-learn?pullRequest=24) it.</sub>

2023-07-10 08:51 UTC, immavalls requested changes
LGTM, I would only do some changes for clarity: https://developers.google.com/tech-writing/one/lists-and-tables

2023-07-10 08:51 UTC, immavalls commented on README.md
> +First, go to the main page: https://github.com/grafana/k6-learn. Fork the repository by clicking the "Fork" button. You should be redirected to your github /username/k6-learn. Now if everything is ok
Thanks for writing this! 

I would use a bullet list, as it's clearer. 

And I'd suggest not mention to commands that users should know and can change depending on how you work. Or if GitHub changes in the future. E.g. for minor typos or changing a single markdown page I usually do that on GitHub without cloning locally. If we want to explain a bit how to collaborate with forks, we can probably add some links to GitHub docs (and keep and eye if they change urls/content). My suggestion below:

```suggestion
1. If there an issue does not exist, start by creating it under https://github.com/grafana/k6-learn/issues.
2. [Fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks) this [repository](https://github.com/grafana/k6-learn). 
3. Make the changes in your forked repository. Note that new branches, changes and pushes will only affect your repository.
4. Once ready, create a [Pull Request fro your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), mentioning the issue it solves (step 1). Keep in mind you might need to [sync it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).
5. Once you have the create the Pull Request, your changes now will be reviewed and either accepted or you will be asked for modifications.
```

2023-07-10 09:37 UTC, kwidera commented on README.md
> +4. Once ready, create a [Pull Request fro your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-reques
```suggestion
4. Once ready, create a [Pull Request from your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), mentioning the issue it solves (step 1). Keep in mind you might need to [sync it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).
```

2023-07-10 09:37 UTC, kwidera commented on README.md
> +5. Once you have the create the Pull Request, your changes now will be reviewed and either accepted or you will be asked for modifications.
```suggestion
5. Once you have created the Pull Request, your changes now will be reviewed and either accepted or you will be asked for modifications.
```

2023-07-10 09:38 UTC, immavalls approved these changes

2023-07-10 10:01 UTC, closed without merging